In [2]:
%pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandasql) (1.24.3)
Requirement already satisfied: pandas in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandasql) (2.0.35)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandas->pandasql) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from sqlalchemy->pandasql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from sqlalchemy->pandasql) (3.1.0)
Requirement already satisfied: six>=1.5 in /home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=5d646ef349d2c7b6e2b59768e34b7ece15d7ebe1c3f6bf12c1c0a18efc4bbf75
  Stored in directory: /home/yogesh/.cache/pip/wheels/68/5d/a5/edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from pandasql import sqldf # type: ignore

In [5]:
# Create a Pandas DataFrame
df = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

df

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

In [3]:
# Define a SQL query
query = "SELECT * FROM df WHERE id > 1"

In [7]:
# Execute SQL query on DataFrame
result = sqldf(query, locals())

# Print the result
print(result)
print(type(result))
result

   id     name
0   2      Bob
1   3  Charlie
<class 'pandas.core.frame.DataFrame'>

   id     name
0   2      Bob
1   3  Charlie